version: '3.8'

services:
  ieshlanz-db:
    image: mysql:8.0
    container_name: ieshlanz-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ieshlanz
      MYSQL_ROOT_PASSWORD: ServidorXover2025
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ieshlanz_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ieshlanz_mysql_data:
